- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~']

- shell:
  -
    command: zsh .prezto
    description: Installing Prezto.
    stdout: true
    stderr: true
  -
    command: sh .vim-plug
    description: Installing vim-plug.
    stdout: true
    stderr: true

- link:
    ~/.zlogin:
    ~/.zlogout:
    ~/.zprofile:
    ~/.zshenv:
    ~/.zshrc:
    ~/.zpreztorc:
    ~/.streamlinkrc:
    ~/.wgetrc:
    ~/.gitconfig:
    ~/.backupignore:
    ~/.config/nvim/init.vim:
      path: init.vim
    ~/Library/LaunchAgents/local.backup.plist:
      path: local.backup.plist
    /usr/local/bin/brew_init:
      path: bin/brew_init
    /usr/local/bin/imgcat:
      path: bin/imgcat
    /usr/local/bin/+x:
      path: bin/+x
    /usr/local/bin/mit:
      path: bin/mit
    /usr/local/bin/backup:
      path: bin/backup
    /usr/local/bin/gpg_wrap:
      path: bin/gpg_wrap

- create:
    - ~/Temp

- shell:
  - [chmod +x /usr/local/bin/imgcat, Setting permissions for imgcat.]
  - [chmod +x /usr/local/bin/+x, Setting permissions for +x.]
  - [chmod +x /usr/local/bin/mit, Setting permissions for mit.]
  - [chmod +x /usr/local/bin/backup, Setting permissions for backup.]
  - [chmod +x /usr/local/bin/gpg_wrap, Setting permissions for gpg_wrap.]
  - [nvim +PlugInstall +qall, Installing Vim plugins.]
